animalapp/animal_resources/urls.py
from django.urls import path

from . import views

app_name = 'animals'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/animal/', views.AnimalDetailView.as_view(), name='animal_detail'),
    path('<int:pk>/dewormings/', views.AnimalDewormingDetailView.as_view(), name='animal_deworming_detail'),
    path('<int:pk>/treatments/', views.AnimalDiseaseAndTreatmentDetailView.as_view(),
         name='animal_disease_and_treatment_detail'),
    path('<int:pk>/ticks/', views.AnimalRemediesForTicksDetailView.as_view(), name='animal_remedies_for_ticks_detail'),
    path('<int:pk>/vaccines/', views.AnimalVaccineDetailView.as_view(), name='animal_vaccine_detail'),
    path('<int:pk>/weight/', views.AnimalWeightDetailView.as_view(), name='animal_weight_detail'),
    path('<int:pk>/information/', views.AnimalGeneralInformationDetailView.as_view(),
         name='animal_general_information_detail'),

    path('add/', views.create_animal, name='animal_form'),
    path('<int:pk>/dewormings/add/', views.create_animal_deworming, name='add_animal_deworming'),
    path('<int:pk>/treatments/add/', views.create_animal_treatment,
         name='add_animal_disease_and_treatment'),
    path('<int:pk>/ticks/add/', views.create_animal_remedy_for_ticks,
         name='add_animal_remedies_for_ticks'),
    path('<int:pk>/vaccines/add/', views.create_animal_vaccine, name='add_animal_vaccine'),
    path('<int:pk>/weight/add/', views.create_animal_weight, name='add_animal_weight'),
    path('<int:pk>/information/add/', views.create_animal_general_information,
         name='add_animal_general_information'),

    path('<int:pk>/animal/modify/', views.update_animal, name='animal_detail'),
    path('<int:pk>/dewormings/modify/<int:id>/', views.update_animal_deworming, name='modify_animal_deworming'),
    path('<int:pk>/treatments/modify/', views.update_animal_treatment, name='modify_animal_disease_and_treatment'),
    path('<int:pk>/ticks/modify/', views.update_animal_remedy_for_ticks, name='modify_animal_remedies_for_ticks'),
    path('<int:pk>/vaccines/modify/', views.update_animal_vaccine, name='modify_animal_vaccine'),
    path('<int:pk>/weight/modify/', views.update_animal_weight, name='modify_animal_weight'),
    path('<int:pk>/information/modify/', views.update_animal_general_information,
         name='modify_animal_general_information'),
]

animalapp/animalapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'animalapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('animals/', include('animal_resources.urls')),
    path('resources/', include('resources.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animalapp/animal_resources/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.utils import timezone

from resources.models import DewormingRemedy, TreatmentAndDisease, VetClinic, RemedyForTicks, Vaccine


# TODO add a validation of date_died and similar dates in other models so the date_died cannot be earlier or equal to
#  date_born

class Animal(models.Model):
    GENDER_CHOICES = [('ML', 'samiec'), ('FM', 'samica')]

    animal_name = models.CharField('Imię', max_length=64)
    species = models.CharField('Gatunek', max_length=64)
    breed = models.CharField('Rasa', max_length=128)
    gender = models.CharField('Płeć', max_length=2, choices=GENDER_CHOICES, default='ML')
    date_born = models.DateTimeField('Data urodzenia', validators=[MaxValueValidator(limit_value=timezone.now())])
    date_died = models.DateTimeField('Data śmierci (opcjonalne)', blank=True, null=True)
    current_weight = models.FloatField('Waga')
    fur_ointment = models.CharField('Maść', max_length=32)
    is_archived = models.BooleanField('Zarchiwizowany?', default=False)
    photo = models.ImageField('Zdjęcie (opcjonalne)', upload_to='animal_resources/animal_photos', blank=True,
                              null=True)

    def __str__(self):
        return self.animal_name


class AnimalDeworming(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    deworming_date = models.DateTimeField('Data odrobaczenia',
                                          validators=[MaxValueValidator(limit_value=timezone.now())])
    deworming_expiration_date = models.DateTimeField('Data ważności')
    deworming_remedy = models.ForeignKey(DewormingRemedy, on_delete=models.PROTECT)

    @property
    def deworming_remedy_name(self):
        return self.deworming_remedy.deworming_remedy_name

    @property
    def animal_name(self):
        return self.animal.animal_name


class AnimalTreatmentAndDisease(models.Model):
    SATISFACTION_LEVEL = [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]

    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    treatment_and_disease = models.ForeignKey(TreatmentAndDisease, on_delete=models.PROTECT)
    vet_clinic = models.ForeignKey(VetClinic, on_delete=models.PROTECT)
    date_occurred = models.DateTimeField('Data rozpoczecia leczenia',
                                         validators=[MaxValueValidator(limit_value=timezone.now())])
    date_treated = models.DateTimeField('Data zakończenia leczenia')
    meds_given = models.CharField('Podane leki (opcjonalne)', max_length=256, blank=True, null=True)
    treatment_cost = models.IntegerField('Koszt leczenia')
    description = models.CharField('Opis leczenia', max_length=256)
    satisfaction = models.IntegerField('Satysfakcja z leczenia', choices=SATISFACTION_LEVEL, default=5)
    doctor = models.CharField('Lekarz prowadzący (opcjonalne)', max_length=32, blank=True, null=True)

    @property
    def treatment_and_disease_name(self):
        return self.treatment_and_disease.treatment_and_disease_name

    @property
    def vet_clinic_name(self):
        return self.vet_clinic.vet_clinic_name

    @property
    def animal_name(self):
        return self.animal.animal_name


class AnimalRemedyForTicks(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    remedy_for_ticks = models.ForeignKey(RemedyForTicks, on_delete=models.PROTECT)
    application_date = models.DateTimeField('Data aplikacji',
                                            validators=[MaxValueValidator(limit_value=timezone.now())])
    expiration_date = models.DateTimeField('Data ważności')

    @property
    def remedy_for_ticks_name(self):
        return self.remedy_for_ticks.remedy_for_ticks_name

    @property
    def animal_name(self):
        return self.animal.animal_name


class AnimalVaccine(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    vaccine = models.ForeignKey(Vaccine, on_delete=models.PROTECT)
    date_of_vaccination = models.DateTimeField('Data szczepienia',
                                               validators=[MaxValueValidator(limit_value=timezone.now())])
    date_of_expiration = models.DateTimeField('Data ważności')

    @property
    def animal_name(self):
        return self.animal.animal_name

    @property
    def vaccine_name(self):
        return self.vaccine.vaccine_name


class AnimalWeight(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    date_of_measurement = models.DateTimeField('Data pomiaru',
                                               validators=[MaxValueValidator(limit_value=timezone.now())])
    weight = models.FloatField()

    @property
    def animal_name(self):
        return self.animal.animal_name


class AnimalGeneralInformation(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.PROTECT)
    content = models.CharField('Opis', max_length=512)

    @property
    def animal_name(self):
        return self.animal.animal_name

animalapp/animal_resources/forms.py
from django.forms import ModelForm
from .models import Animal, AnimalDeworming, AnimalTreatmentAndDisease, AnimalRemedyForTicks, AnimalVaccine, \
    AnimalWeight, AnimalGeneralInformation


class AnimalForm(ModelForm):
    class Meta:
        model = Animal
        fields = ['animal_name', 'species', 'breed', 'gender', 'date_born', 'current_weight', 'fur_ointment',
                  'is_archived', 'photo']


class AnimalDewormingForm(ModelForm):
    class Meta:
        model = AnimalDeworming
        fields = ['animal', 'id', 'deworming_date', 'deworming_expiration_date', 'deworming_remedy']


class AnimalTreatmentAndDiseaseForm(ModelForm):
    class Meta:
        model = AnimalTreatmentAndDisease
        fields = ['animal', 'treatment_and_disease', 'vet_clinic', 'date_occurred', 'date_treated', 'meds_given',
                  'treatment_cost', 'description', 'satisfaction', 'doctor']


class AnimalRemedyForTicksForm(ModelForm):
    class Meta:
        model = AnimalRemedyForTicks
        fields = ['animal', 'remedy_for_ticks', 'application_date', 'expiration_date']


class AnimalVaccineForm(ModelForm):
    class Meta:
        model = AnimalVaccine
        fields = ['animal', 'vaccine', 'date_of_vaccination', 'date_of_expiration']


class AnimalWeightForm(ModelForm):
    class Meta:
        model = AnimalWeight
        fields = ['animal', 'date_of_measurement', 'weight']


class AnimalGeneralInformationForm(ModelForm):
    class Meta:
        model = AnimalGeneralInformation
        fields = ['animal', 'content']

animalapp/animal_resources/templates/animal_resources/create/create_animal.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        <div id="logo">AnimalApp Zwierzęta</div>
        <div class="button"><a href="/animals/">Zwierzęta główna</a></div>


        <div id="content" style="clear:both;">
            <form action="/animals/add/" method="post">
                {% csrf_token %}

                <label for="id_animal_name">Imię:</label>
                <input type="text" name="animal_name" maxlength="64" required id="id_animal_name"></br></br>

                <label for="id_species">Gatunek:</label>
                <input type="text" name="species" maxlength="64" required id="id_species"></br></br>

                <label for="id_breed">Rasa:</label>
                <input type="text" name="breed" maxlength="128" required id="id_breed"></br></br>

                <label for="id_gender">Płeć:</label>
                <select name="gender" id="id_gender">
                    <option value="ML" selected>samiec</option>
                    <option value="FM">samica</option>
                </select></br></br>

                <label for="id_date_born">Data urodzenia:</label>
                <input type="text" name="date_born" required id="id_date_born"></br></br>

                <label for="id_current_weight">Waga:</label>
                <input type="number" name="current_weight" step="any" required id="id_current_weight"></br></br>

                <label for="id_fur_ointment">Maść:</label>
                <input type="text" name="fur_ointment" maxlength="32" required id="id_fur_ointment"></br></br>

                <label for="id_is_archived">Zarchiwizowany?</label>
                <input type="checkbox" name="is_archived" id="id_is_archived"></br></br>

                <label for="id_photo">Zdjęcie (opcjonalne):</label>
                <input type="file" name="photo" accept="image/*" id="id_photo"></br></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_deworming.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD GG:MM:SS</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/dewormings/add/" method="post">
                {% csrf_token %}
                <input type="hidden" name="animal" required id="id_animal" value={{pk}}>

                <label for="id_deworming_date">Data odrobaczenia:</label>
                <input type="text" name="deworming_date" required id="id_deworming_date"></br></br>

                <label for="id_deworming_expiration_date">Data ważności:</label>
                <input type="text" name="deworming_expiration_date" required id="id_deworming_expiration_date"></br></br>

                <label for="id_deworming_remedy">Deworming remedy:</label>
                <select name="deworming_remedy" required id="id_deworming_remedy">
                    {% for remedy in form.deworming_remedy %}
                        {{remedy}}
                    {% endfor %}
                </select></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_information.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD GG:MM:SS</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/information/add/" method="post">
                {% csrf_token %}

<!--                <input type="hidden" name="animal" required id="id_animal" value={{pk}}>-->

<!--                <label for="id_content">Opis:</label>-->
<!--                <input type="text" name="content" maxlength="512" required id="id_content"></br></br></br>-->
                {% if form=="AnimalGeneralInformationForm" %}
                    Dupa
                {% endif %}

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_remedy_for_ticks.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/ticks/add/" method="post">
                {% csrf_token %}

                <input type="hidden" name="animal" required id="id_animal" value={{pk}}></br></br>

                <label for="id_remedy_for_ticks">Remedy for ticks:</label>
                <select name="remedy_for_ticks" required id="id_remedy_for_ticks">
                    {% for remedy in form.remedy_for_ticks %}
                        {{remedy}}
                    {% endfor %}
                </select></br></br>

                <label for="id_application_date">Data aplikacji:</label>
                <input type="text" name="application_date" required id="id_application_date"></br></br>

                <label for="id_expiration_date">Data ważności:</label>
                <input type="text" name="expiration_date" required id="id_expiration_date"></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_treatment.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD GG:MM:SS</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/treatments/add/" method="post">
                {% csrf_token %}

                <input type="hidden" name="animal" required id="id_animal" value={{pk}}>

                <label for="id_treatment_and_disease">Zabieg lub choroba:</label>
                <select name="treatment_and_disease" required id="id_treatment_and_disease">
                    {% for tre in form.treatment_and_disease %}
                        {{tre}}
                    {% endfor %}
                </select></br></br>

                <label for="id_vet_clinic">Klinika weterynaryjna:</label>
                <select name="vet_clinic" required id="id_vet_clinic">
                    {% for cli in form.vet_clinic %}
                        {{cli}}
                    {% endfor %}
                </select></br></br>

                <label for="id_date_occurred">Data rozpoczecia leczenia:</label>
                    <input type="text" name="date_occurred" required id="id_date_occurred"></br></br>

                <label for="id_date_treated">Data zakończenia leczenia:</label>
                <input type="text" name="date_treated" required id="id_date_treated"></br></br>

                <label for="id_meds_given">Podane leki (opcjonalne):</label>
                <input type="text" name="meds_given" maxlength="256" id="id_meds_given"></br></br>

                <label for="id_treatment_cost">Koszt leczenia:</label>
                <input type="number" name="treatment_cost" required id="id_treatment_cost"></br></br>

                <label for="id_description">Opis leczenia:</label>
                <input type="text" name="description" maxlength="256" required id="id_description"></br></br>

                <label for="id_satisfaction">Satysfakcja z leczenia:</label>
                <select name="satisfaction" id="id_satisfaction">
                    {% for sat in form.satisfaction %}
                        {{sat}}
                    {% endfor %}
                </select></br></br>

                <label for="id_doctor">Lekarz prowadzący (opcjonalne):</label>
                <input type="text" name="doctor" maxlength="32" id="id_doctor"></br></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_vaccine.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD GG:MM:SS</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/vaccines/add/" method="post">
                {% csrf_token %}

                <input type="hidden" name="animal" required id="id_animal" value={{pk}}>

                <label for="id_vaccine">Vaccine:</label>
                <select name="vaccine" required id="id_vaccine">
                    {% for vac in form.vaccine %}
                        {{vac}}
                    {% endfor %}
                </select></br></br>

                <label for="id_date_of_vaccination">Data szczepienia:</label>
                <input type="text" name="date_of_vaccination" required id="id_date_of_vaccination"></br></br>

                <label for="id_date_of_expiration">Data ważności:</label>
                <input type="text" name="date_of_expiration" required id="id_date_of_expiration"></br></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>

animalapp/animal_resources/templates/animal_resources/create/create_animal_weight.html
<!DOCTYPE HTML>
{% load static %}
<html lang="pl">
    <head>
        {% include "../head.html" %}
    </head>

    <body>
        {% include "../menus_for_create_modify.html" %}

        <h3>Daty podawać w formacie:<p style="color: red;">RRRR-MM-DD GG:MM:SS</p></h3>

        <div id="content" style="clear:both;">
            <form action="/animals/{{pk}}/weight/add/" method="post">
                {% csrf_token %}

                <input type="hidden" name="animal" required id="id_animal" value={{pk}}>

                <label for="id_date_of_measurement">Data pomiaru:</label>
                <input type="text" name="date_of_measurement" required id="id_date_of_measurement"></br></br>

                <label for="id_weight">Weight:</label>
                <input type="number" name="weight" step="any" required id="id_weight"></br></br></br>

                <input type="submit" value="Dodaj">
            </form>
        </div>
    </body>
</html>